### ISSUE TITLE
Can't change publishing branch

### ISSUE THREAD

**Issue by alebianco** [qiwi/semantic-release-gh-pages-plugin#11]
Can't configure the branch where to publish the site content. This is needed in order to publish user or organisation pages.

The option is being stripped when resolving the configuration in attempt to ignore semantic-release's own branch value. Introduced by v1.1.1 because of #5 

https://github.com/qiwi/semantic-release-gh-pages-plugin/blob/master/src/main/config.ts#L59

Probably the best course of action would be to change parameter name.

**Comment by antongolub** [comment]
[Sad but true](https://github.com/semantic-release/semantic-release/blob/master/lib/get-config.js). 
```javascript
// If `extends` is defined, load and merge each shareable config with `options`
```
For now, you're still able to define `branch` opt as a part of step-specific plugin config:
```javascript
// ...
publish: [
  // ...
  ['@qiwi/semantic-release-gh-pages-plugin', {branch: 'gh-pages'}]
]
```
I need to take a closer look at the sem-rel config resolver.

**Comment by alebianco** [comment]
thanks for the suggestion but even with that, it always publish to `gh-pages`. I need to be able to publish to `master` or to any other branch really

**Comment by antongolub** [comment]
@pvdlg, could you help us with this issue?
Looks like pluginConfig ignores `branch` option, but respects other. I did a couple of experiments: [#1](https://github.com/qiwi/common-formatters/commit/dddecc37a5cd0faa0918934a61b2595902afd13f), [#2](https://github.com/qiwi/common-formatters/commit/caedf50ac178ac0157e094b1b9b9664fa439a911)

The first proves that `branch` option was omitted, the second shows that `msg` option was passed as expected.

Config resolver:
```javascript
export const resolveOptions = (pluginConfig: TAnyMap, context: TContext, path = PLUGIN_PATH, step?: string): TAnyMap => {
  const { options } = context
  const base = pluginConfig[path] || {}
  const extra = step && options[step] && castArray(options[step])
    .find(config => get(config, 'path') === path) || {}

  return { ...base, ...extra }
}

export const resolveConfig = (pluginConfig: TAnyMap, context: TContext, path = PLUGIN_PATH, step?: string): IGhpagesPluginConfig => {
  const { env } = context
  const opts = resolveOptions(pluginConfig, context, path, step)
  const token = getToken(env)
  const repo = getRepo(context)

  return {
    src: opts.src || DEFAULT_SRC,
    dst: opts.dst || DEFAULT_DST,
    msg: opts.msg || DEFAULT_MSG,
    branch: opts.branch || DEFAULT_BRANCH,
    token,
    repo
  }
}
```

**Comment by antongolub** [comment]
@alebianco , finally I got it:
```json
"publish": [
      "@semantic-release/npm",
      "@semantic-release/github",
      {
        "path": "@qiwi/semantic-release-gh-pages-plugin",
        "msg": "updated",
        "branch": "docs"
      }
    ]
```

**Comment by alebianco** [comment]
I'm not 100% sure how but this workaround seems to work, thank you

**Comment by iamogbz** [comment]
@antongolub running into this right now, there might have been a regression? Or maybe something changed on semantic release side.

Either way I have tried a bunch of different valid configurations and it still always pushes to `gh-pages`

```js
publish: [
  // ...
  ['@qiwi/semantic-release-gh-pages-plugin', {branch: 'releaseBranch'}]
]
```
```js
plugins: [
  // ...
  {path: '@qiwi/semantic-release-gh-pages-plugin', branch: 'releaseBranch'}]
]
```

**Comment by antongolub** [comment]
Hey, @iamogbz, 

What does print debug if enabled?
```
debug('pluginConfig= %j', pluginConfig)
```
