### ISSUE TITLE
Must it be released with NPM?

### ISSUE THREAD

**Issue by 1977474741** [qiwi/semantic-release-gh-pages-plugin#192]
This is my releaserc configuration file.
[https://github.com/1977474741/spa-custom-hooks/blob/0b01651c8cd0f451a0e446e3e47bdda052b66bc0/.releaserc#L31](https://github.com/1977474741/spa-custom-hooks/blob/0b01651c8cd0f451a0e446e3e47bdda052b66bc0/.releaserc#L31)
I want to update GH pages without uploading them to NPM, but I can't do it now. Can the execution timing of the two be the same?

**Comment by antongolub** [comment]
Not sure if that's possible to completely disable the npm plugin, but you can [mark your pkg as private](https://github.com/semantic-release/semantic-release/blob/bd664bdf6ad597adab9220934a569dc18c612223/docs/support/FAQ.md?plain=1#L11), so it will not be published.

**Comment by 1977474741** [comment]
> 不确定是否可以完全禁用 npm 插件，但您可以将[您的 pkg 标记为 private](https://github.com/semantic-release/semantic-release/blob/bd664bdf6ad597adab9220934a569dc18c612223/docs/support/FAQ.md?plain=1#L11)，这样它就不会被发布。

不行，这个包还是要发的，只是不是本次提交，我理想的方式是在需要发布npm的时候，在提交信息上加一个 --publish？因为一个项目不仅包含了需要发布的包，可能还包含demo，和其他相关的东西等等，如果我本次只改了demo，就不需要发布
