### ISSUE TITLE
Migration to `zurk` causes CI failure

### ISSUE THREAD

**Issue by jeswr** [qiwi/semantic-release-gh-pages-plugin#282]
## Issue type
* [x] bug report
* [ ] idea
* [ ] question
* [ ] other

## Expected behavior
GH Pages to continue to be published as usual

## Actual behavior
Fails with error `TypeError: (0 , zurk_1.$)(...)(...).catch is not a function`. An example of such a failing job can be found at https://github.com/eyereasoner/eye-js/actions/runs/12236225074/job/34129931769

* [x] I've read the docs. This case is not mentioned
* [x] Similar issue does not exist

## Steps to reproduce
See https://github.com/eyereasoner/eye-js/actions/runs/12236225074/job/34129931769

## Specifications
See https://github.com/eyereasoner/eye-js/blob/d07fb2207619a3d785b4befcb93e68761b73ae67/.github/workflows/nodejs.yml#L110-L141

**Comment by antongolub** [comment]
Wow! This is how tsc compiles
```ts
$`cmd`.catch
```
```js
return (0, zurk_1.$)({
        env: opts.env,
        cwd: opts.cwd,
        shell: false
    })(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["git pull --tags --force ", " ", ""], ["git pull --tags --force ", " ", ""])), repo, pullTagsBranch).catch(console.error);
```

**Comment by antongolub** [comment]
@jeswr,

v5.4.1 is on the way
